### PR TITLE
Create coinciding_events.rst

### PR DESCRIPTION
**Pull request by fgregg**
Proposal for coinciding events.

### CODE REVIEW

**Comment by paultag** [comment]
Why not extend the related entities stuff?

**Comment by fgregg** [comment]
That would suggest that one event is the parent event, wouldn't it? I don't think that's right.

**Comment by paultag** [comment]
for a related event? Not that I know of - an event presenter isn't the parent of the event

**Comment by fgregg** [comment]
I agree it would be good to have these coinciding events be referenced in each other in a 'related_events' like field. But in order to do that, all the coinciding events would have to be in the database. Right now they can't be because of the duplicate detection.

**Comment by paultag** [comment]
Dupe unduping would only happen if they have the same description

**Comment by paultag** [comment]
So this is to support two events that look identical but actually aren't? Do you mean Agenda? I don't understand this yet

**Comment by fgregg** [comment]
See https://github.com/opencivicdata/scrapers-us-municipal/pull/29#issue-77710072

**Comment by paultag** [comment]
https://github.com/opencivicdata/pupa/blob/master/pupa/importers/events.py#L31-L40

Unless they all match, it's not a dupe. Something else is going on.

Closing this, we don't need to modify the schema to work around this stuff. At most we'd adjust events, but I don't understand why we would need to yet -- if they dupe, that would mean the objects have the same `name`, `description`, `start_time`, `end_time`, `timezone`, and `jurisdiction`. I don't think that's the case with two events at the same time, since they'd have unique `name`/`descriptions`

**Pull request closed without merging**
