### PR TITLE
Create documents.rst

### PR DESCRIPTION
**Pull request by fgregg**
Proposal for document class.

### CODE REVIEW

**Comment by boblannon** [comment]
want to second this, on the record.  in fact, by the time it was fully whittled down, my proposed `Disclosure` object really started to feel more like a general document/record object.  See #36

**Comment by fgregg** [comment]
@boblannon 

Okay. took a pass in pulling out generalizable stuff from bills. I'm not sure if all the things in 'additional fields' should land in the document class or a disclosure subclass.

Also, I feel it's kind of weird for a document to have versions. it seems like those versions should be... documents. Maybe we should just have related documents? 

Also, @jamesturk this work might be relevant to what you are doing with relatedbilldocument.

**Comment by fgregg** [comment]
Alright, I think we now have something workable for our Document needs in Chicago.

The big change I've made here is to now allow a Document to have _versions_ instead, I think that Dcouments should be a more atomic type. 

Could I get some feedback on this proposal, @boblannon @jamesturk

**Comment by boblannon** [comment]
:+1: 

How would you link related `Events`?  Just through `related_entities`?

**Comment by fgregg** [comment]
I haven't thought a lot about Events. What do you need to relate? What's your use case?

**Comment by boblannon** [comment]
an example would be a disclosure document (like a quarterly lobbying report) that discloses many events (like meetings, etc). another would be a campaign finance filling that reports many transactions. as i said, i think that `related_entities`is the right place for this

**Comment by fgregg** [comment]
I think related_entities would be a good place for this generally. But, Campaign Disclosures should probably be a subclass of Documents since you would want to model things like reporting period, periodicity, and the like.

**Comment by boblannon** [comment]
Sure, agreed

**Comment by fgregg** [comment]
Okay, how do I proceed? Should I get this PEP accepted before implementing the proposal or provide a reference implementation with the proposal?

**Comment by jamesturk** [comment]
No need to wait to get started, I think this is pretty much good to go, a
few minor suggestions after a quick look:

could we change the places the descriptions of fields mention bill to say
document?

s/full_text/text would match the WIP text stuff I've done in pupa

**Comment by jpmckinney** [comment]
Is is worthwhile to review this PR?

**Comment by fgregg** [comment]
no.

**Pull request closed without merging**
