### PR TITLE
Use the superclass Agent instead of overloading Person

### PR DESCRIPTION
**Pull request by jpmckinney**
@aepton

### CODE REVIEW

**Comment by jpmckinney** [comment]
Ping @aepton

**Comment by jpmckinney** [comment]
Actually, should probably just handle this the way [Bill handles sponsorships](http://docs.opencivicdata.org/en/latest/proposals/0006.html).

**Comment by aepton** [comment]
Submitted a PR that does this

**Comment by jpmckinney** [comment]
Closed by #71 and d7e4e26c647bc91b4d955439db3233d12db34294

Follow-up in #74

**Pull request closed without merging**
